COPY artists FROM '/Users/harrisonobeid/Documents/AirCloudy/Related-Tracks/database/data/artist.csv' DELIMITER ',' CSV HEADER;
COPY users FROM '/Users/harrisonobeid/Documents/AirCloudy/Related-Tracks/database/data/user.csv' DELIMITER ',' CSV HEADER;
COPY genres FROM '/Users/harrisonobeid/Documents/AirCloudy/Related-Tracks/database/data/genre.csv' DELIMITER ',' CSV HEADER;
COPY albums FROM '/Users/harrisonobeid/Documents/AirCloudy/Related-Tracks/database/data/album.csv' DELIMITER ',' CSV HEADER;
COPY songs FROM '/Users/harrisonobeid/Documents/AirCloudy/Related-Tracks/database/data/song.csv' DELIMITER ',' CSV HEADER;
COPY playlists FROM '/Users/harrisonobeid/Documents/AirCloudy/Related-Tracks/database/data/playlist.csv' DELIMITER ',' NULL AS 'null' CSV HEADER;
COPY likes FROM '/Users/harrisonobeid/Documents/AirCloudy/Related-Tracks/database/data/likes.csv' DELIMITER ',' NULL AS 'null' CSV HEADER;
COPY reposts FROM '/Users/harrisonobeid/Documents/AirCloudy/Related-Tracks/database/data/reposts.csv' DELIMITER ',' NULL AS 'null' CSV HEADER;
COPY song_to_genre FROM '/Users/harrisonobeid/Documents/AirCloudy/Related-Tracks/database/data/song_genre.csv' DELIMITER ',' CSV HEADER;
COPY song_to_playlist FROM '/Users/harrisonobeid/Documents/AirCloudy/Related-Tracks/database/data/song_playlist.csv' DELIMITER ',' CSV HEADER;